### ISSUE TITLE
Build Failure on Jammy(Ubuntu 22.04)

### ISSUE THREAD

**Issue by paranlee** [facebookincubator/below#8141]
Hello, I have compiled `below` on latest ubuntu 22.04 jammy.

Looks like dependency  `libbpf-sys v0.6.2+v0.6.1` has an issue.

```
  Compiling crossbeam-deque v0.8.1
   Compiling signal-hook-mio v0.2.3
   Compiling libbpf-sys v0.6.2+v0.6.1
   Compiling zstd-sys v1.5.0+zstd.1.4.9
   Compiling vsprintf v2.0.0
   Compiling console v0.15.0
   Compiling crossterm v0.19.0
   Compiling darling_core v0.10.2
   Compiling term v0.7.0
   Compiling crossterm v0.20.0
   Compiling num v0.3.1
error: failed to run custom build command for `libbpf-sys v0.6.2+v0.6.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install9Iwpfi/release/build/libbpf-sys-d272316adf9e8884/build-script-build` (exit status: 101)
  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /home/paran/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-0.6.2+v0.6.1/build.rs:81:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `below v0.5.0`, intermediate artifacts can be found at `/tmp/cargo-install9Iwpfi`
paran@paran-virtual-machine:~/below$ uname -a
Linux paran-virtual-machine 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

What contribution can I make to help this issue?

Thanks.
Paran Lee.

**Comment by brianc118** [comment]
I just tried building docker image with below and it works fine for me:

```
cargo

```
ubuntu@instance-20210906-1041: $ podman build -t below .
# ...
[2/2] STEP 6/6: ENTRYPOINT ["/below"]
[2/2] COMMIT below
--> f93b7a099a4
Successfully tagged localhost/below:latest
f93b7a099a40628908aa00e37e9aceb6dc07081df49187a3724efe5cc8fdb407
ubuntu@instance-20210906-1041:~/dev/below$ git diff
diff --git a/Dockerfile b/Dockerfile
index 88b42d9..7d796be 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:20.04 AS build
+FROM ubuntu:22.04 AS build

 ARG DEBIAN_FRONTEND=noninteractive
 RUN apt-get update && apt-get install -y \
@@ -30,7 +30,7 @@ RUN /root/.cargo/bin/cargo build --release --all-targets
 # Now create stage 2 image. We drop all the build dependencies and only install
 # runtime dependencies. This will create a smaller image suitable for
 # distribution.
-FROM ubuntu:20.04
+FROM ubuntu:22.04

 # Default locale is "POSIX" which doesn't seem to play well with UTF-8. Cursive
 # uses UTF-8 to draw lines so we need to set this locale otherwise our lines
 ```

**Comment by brianc118** [comment]
@paranlee your build is failing at the build libbpf-sys step, with error
```
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /home/paran/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-0.6.2+v0.6.1/build.rs:81:13
```
it sounds like you don't have pkg-config installed?

**Comment by brianc118** [comment]
You need to install the following: https://github.com/facebookincubator/below/blob/main/Dockerfile#L4-L16

**Comment by paranlee** [comment]
@brianc118 Thank you!
I'll install pkg-config package, try build, give you feedback.
